#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MRC")]
public partial class MRCDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertMenu(Menu instance);
  partial void UpdateMenu(Menu instance);
  partial void DeleteMenu(Menu instance);
  partial void InsertPuesto(Puesto instance);
  partial void UpdatePuesto(Puesto instance);
  partial void DeletePuesto(Puesto instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  partial void InsertRol(Rol instance);
  partial void UpdateRol(Rol instance);
  partial void DeleteRol(Rol instance);
  partial void InsertPuestoMenu(PuestoMenu instance);
  partial void UpdatePuestoMenu(PuestoMenu instance);
  partial void DeletePuestoMenu(PuestoMenu instance);
  #endregion
	
	public MRCDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MRCConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MRCDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MRCDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MRCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MRCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Menu> Menu
	{
		get
		{
			return this.GetTable<Menu>();
		}
	}
	
	public System.Data.Linq.Table<Puesto> Puesto
	{
		get
		{
			return this.GetTable<Puesto>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
	
	public System.Data.Linq.Table<ObtenerSubMenuPuesto> ObtenerSubMenuPuesto
	{
		get
		{
			return this.GetTable<ObtenerSubMenuPuesto>();
		}
	}
	
	public System.Data.Linq.Table<Rol> Rol
	{
		get
		{
			return this.GetTable<Rol>();
		}
	}
	
	public System.Data.Linq.Table<PuestoMenu> PuestoMenu
	{
		get
		{
			return this.GetTable<PuestoMenu>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerMenuPuesto")]
	public ISingleResult<ObtenerMenuPuestoResult> ObtenerMenuPuesto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDP", DbType="Int")] System.Nullable<int> iDP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDP);
		return ((ISingleResult<ObtenerMenuPuestoResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDM;
	
	private string _NombreM;
	
	private bool _TipoM;
	
	private System.Nullable<int> _IDPadreM;
	
	private string _IconoM;
	
	private string _URLM;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMChanging(int value);
    partial void OnIDMChanged();
    partial void OnNombreMChanging(string value);
    partial void OnNombreMChanged();
    partial void OnTipoMChanging(bool value);
    partial void OnTipoMChanged();
    partial void OnIDPadreMChanging(System.Nullable<int> value);
    partial void OnIDPadreMChanged();
    partial void OnIconoMChanging(string value);
    partial void OnIconoMChanged();
    partial void OnURLMChanging(string value);
    partial void OnURLMChanged();
    #endregion
	
	public Menu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDM
	{
		get
		{
			return this._IDM;
		}
		set
		{
			if ((this._IDM != value))
			{
				this.OnIDMChanging(value);
				this.SendPropertyChanging();
				this._IDM = value;
				this.SendPropertyChanged("IDM");
				this.OnIDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreM", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
	public string NombreM
	{
		get
		{
			return this._NombreM;
		}
		set
		{
			if ((this._NombreM != value))
			{
				this.OnNombreMChanging(value);
				this.SendPropertyChanging();
				this._NombreM = value;
				this.SendPropertyChanged("NombreM");
				this.OnNombreMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoM", DbType="Bit NOT NULL")]
	public bool TipoM
	{
		get
		{
			return this._TipoM;
		}
		set
		{
			if ((this._TipoM != value))
			{
				this.OnTipoMChanging(value);
				this.SendPropertyChanging();
				this._TipoM = value;
				this.SendPropertyChanged("TipoM");
				this.OnTipoMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPadreM", DbType="Int")]
	public System.Nullable<int> IDPadreM
	{
		get
		{
			return this._IDPadreM;
		}
		set
		{
			if ((this._IDPadreM != value))
			{
				this.OnIDPadreMChanging(value);
				this.SendPropertyChanging();
				this._IDPadreM = value;
				this.SendPropertyChanged("IDPadreM");
				this.OnIDPadreMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconoM", DbType="VarChar(200)")]
	public string IconoM
	{
		get
		{
			return this._IconoM;
		}
		set
		{
			if ((this._IconoM != value))
			{
				this.OnIconoMChanging(value);
				this.SendPropertyChanging();
				this._IconoM = value;
				this.SendPropertyChanged("IconoM");
				this.OnIconoMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLM", DbType="VarChar(1000)")]
	public string URLM
	{
		get
		{
			return this._URLM;
		}
		set
		{
			if ((this._URLM != value))
			{
				this.OnURLMChanging(value);
				this.SendPropertyChanging();
				this._URLM = value;
				this.SendPropertyChanged("URLM");
				this.OnURLMChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puesto")]
public partial class Puesto : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDP;
	
	private string _NombreP;
	
	private string _DescripcionP;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPChanging(int value);
    partial void OnIDPChanged();
    partial void OnNombrePChanging(string value);
    partial void OnNombrePChanged();
    partial void OnDescripcionPChanging(string value);
    partial void OnDescripcionPChanged();
    #endregion
	
	public Puesto()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDP
	{
		get
		{
			return this._IDP;
		}
		set
		{
			if ((this._IDP != value))
			{
				this.OnIDPChanging(value);
				this.SendPropertyChanging();
				this._IDP = value;
				this.SendPropertyChanged("IDP");
				this.OnIDPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreP", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreP
	{
		get
		{
			return this._NombreP;
		}
		set
		{
			if ((this._NombreP != value))
			{
				this.OnNombrePChanging(value);
				this.SendPropertyChanging();
				this._NombreP = value;
				this.SendPropertyChanged("NombreP");
				this.OnNombrePChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionP", DbType="VarChar(500)")]
	public string DescripcionP
	{
		get
		{
			return this._DescripcionP;
		}
		set
		{
			if ((this._DescripcionP != value))
			{
				this.OnDescripcionPChanging(value);
				this.SendPropertyChanging();
				this._DescripcionP = value;
				this.SendPropertyChanged("DescripcionP");
				this.OnDescripcionPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDU;
	
	private int _NumeroEmpleadoU;
	
	private string _NombreUsuarioU;
	
	private string _ContrasenaU;
	
	private bool _EstatusU;
	
	private System.Nullable<System.DateTime> _FechaUltimaConexionU;
	
	private System.Nullable<int> _IDPU;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUChanging(int value);
    partial void OnIDUChanged();
    partial void OnNumeroEmpleadoUChanging(int value);
    partial void OnNumeroEmpleadoUChanged();
    partial void OnNombreUsuarioUChanging(string value);
    partial void OnNombreUsuarioUChanged();
    partial void OnContrasenaUChanging(string value);
    partial void OnContrasenaUChanged();
    partial void OnEstatusUChanging(bool value);
    partial void OnEstatusUChanged();
    partial void OnFechaUltimaConexionUChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaUltimaConexionUChanged();
    partial void OnIDPUChanging(System.Nullable<int> value);
    partial void OnIDPUChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroEmpleadoU", DbType="Int NOT NULL")]
	public int NumeroEmpleadoU
	{
		get
		{
			return this._NumeroEmpleadoU;
		}
		set
		{
			if ((this._NumeroEmpleadoU != value))
			{
				this.OnNumeroEmpleadoUChanging(value);
				this.SendPropertyChanging();
				this._NumeroEmpleadoU = value;
				this.SendPropertyChanged("NumeroEmpleadoU");
				this.OnNumeroEmpleadoUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuarioU", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreUsuarioU
	{
		get
		{
			return this._NombreUsuarioU;
		}
		set
		{
			if ((this._NombreUsuarioU != value))
			{
				this.OnNombreUsuarioUChanging(value);
				this.SendPropertyChanging();
				this._NombreUsuarioU = value;
				this.SendPropertyChanged("NombreUsuarioU");
				this.OnNombreUsuarioUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContrasenaU", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string ContrasenaU
	{
		get
		{
			return this._ContrasenaU;
		}
		set
		{
			if ((this._ContrasenaU != value))
			{
				this.OnContrasenaUChanging(value);
				this.SendPropertyChanging();
				this._ContrasenaU = value;
				this.SendPropertyChanged("ContrasenaU");
				this.OnContrasenaUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusU", DbType="Bit NOT NULL")]
	public bool EstatusU
	{
		get
		{
			return this._EstatusU;
		}
		set
		{
			if ((this._EstatusU != value))
			{
				this.OnEstatusUChanging(value);
				this.SendPropertyChanging();
				this._EstatusU = value;
				this.SendPropertyChanged("EstatusU");
				this.OnEstatusUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaConexionU", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaUltimaConexionU
	{
		get
		{
			return this._FechaUltimaConexionU;
		}
		set
		{
			if ((this._FechaUltimaConexionU != value))
			{
				this.OnFechaUltimaConexionUChanging(value);
				this.SendPropertyChanging();
				this._FechaUltimaConexionU = value;
				this.SendPropertyChanged("FechaUltimaConexionU");
				this.OnFechaUltimaConexionUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPU", DbType="Int")]
	public System.Nullable<int> IDPU
	{
		get
		{
			return this._IDPU;
		}
		set
		{
			if ((this._IDPU != value))
			{
				this.OnIDPUChanging(value);
				this.SendPropertyChanging();
				this._IDPU = value;
				this.SendPropertyChanged("IDPU");
				this.OnIDPUChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObtenerSubMenuPuesto")]
public partial class ObtenerSubMenuPuesto
{
	
	private int _IDM;
	
	private string _NombreM;
	
	private bool _TipoM;
	
	private System.Nullable<int> _IDPadreM;
	
	private string _IconoM;
	
	private string _URLM;
	
	private int _IDPM;
	
	private int _IDP;
	
	private bool _EstatusPM;
	
	public ObtenerSubMenuPuesto()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", DbType="Int NOT NULL")]
	public int IDM
	{
		get
		{
			return this._IDM;
		}
		set
		{
			if ((this._IDM != value))
			{
				this._IDM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreM", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
	public string NombreM
	{
		get
		{
			return this._NombreM;
		}
		set
		{
			if ((this._NombreM != value))
			{
				this._NombreM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoM", DbType="Bit NOT NULL")]
	public bool TipoM
	{
		get
		{
			return this._TipoM;
		}
		set
		{
			if ((this._TipoM != value))
			{
				this._TipoM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPadreM", DbType="Int")]
	public System.Nullable<int> IDPadreM
	{
		get
		{
			return this._IDPadreM;
		}
		set
		{
			if ((this._IDPadreM != value))
			{
				this._IDPadreM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconoM", DbType="VarChar(200)")]
	public string IconoM
	{
		get
		{
			return this._IconoM;
		}
		set
		{
			if ((this._IconoM != value))
			{
				this._IconoM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLM", DbType="VarChar(1000)")]
	public string URLM
	{
		get
		{
			return this._URLM;
		}
		set
		{
			if ((this._URLM != value))
			{
				this._URLM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPM", DbType="Int NOT NULL")]
	public int IDPM
	{
		get
		{
			return this._IDPM;
		}
		set
		{
			if ((this._IDPM != value))
			{
				this._IDPM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", DbType="Int NOT NULL")]
	public int IDP
	{
		get
		{
			return this._IDP;
		}
		set
		{
			if ((this._IDP != value))
			{
				this._IDP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusPM", DbType="Bit NOT NULL")]
	public bool EstatusPM
	{
		get
		{
			return this._EstatusPM;
		}
		set
		{
			if ((this._EstatusPM != value))
			{
				this._EstatusPM = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDR;
	
	private string _NombreR;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRChanging(int value);
    partial void OnIDRChanged();
    partial void OnNombreRChanging(string value);
    partial void OnNombreRChanged();
    #endregion
	
	public Rol()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDR
	{
		get
		{
			return this._IDR;
		}
		set
		{
			if ((this._IDR != value))
			{
				this.OnIDRChanging(value);
				this.SendPropertyChanging();
				this._IDR = value;
				this.SendPropertyChanged("IDR");
				this.OnIDRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreR", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreR
	{
		get
		{
			return this._NombreR;
		}
		set
		{
			if ((this._NombreR != value))
			{
				this.OnNombreRChanging(value);
				this.SendPropertyChanging();
				this._NombreR = value;
				this.SendPropertyChanged("NombreR");
				this.OnNombreRChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PuestoMenu")]
public partial class PuestoMenu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDPM;
	
	private int _IDP;
	
	private int _IDM;
	
	private bool _EstatusPM;
	
	private System.Nullable<int> _IDR;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPMChanging(int value);
    partial void OnIDPMChanged();
    partial void OnIDPChanging(int value);
    partial void OnIDPChanged();
    partial void OnIDMChanging(int value);
    partial void OnIDMChanged();
    partial void OnEstatusPMChanging(bool value);
    partial void OnEstatusPMChanged();
    partial void OnIDRChanging(System.Nullable<int> value);
    partial void OnIDRChanged();
    #endregion
	
	public PuestoMenu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDPM
	{
		get
		{
			return this._IDPM;
		}
		set
		{
			if ((this._IDPM != value))
			{
				this.OnIDPMChanging(value);
				this.SendPropertyChanging();
				this._IDPM = value;
				this.SendPropertyChanged("IDPM");
				this.OnIDPMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", DbType="Int NOT NULL")]
	public int IDP
	{
		get
		{
			return this._IDP;
		}
		set
		{
			if ((this._IDP != value))
			{
				this.OnIDPChanging(value);
				this.SendPropertyChanging();
				this._IDP = value;
				this.SendPropertyChanged("IDP");
				this.OnIDPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", DbType="Int NOT NULL")]
	public int IDM
	{
		get
		{
			return this._IDM;
		}
		set
		{
			if ((this._IDM != value))
			{
				this.OnIDMChanging(value);
				this.SendPropertyChanging();
				this._IDM = value;
				this.SendPropertyChanged("IDM");
				this.OnIDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusPM", DbType="Bit NOT NULL")]
	public bool EstatusPM
	{
		get
		{
			return this._EstatusPM;
		}
		set
		{
			if ((this._EstatusPM != value))
			{
				this.OnEstatusPMChanging(value);
				this.SendPropertyChanging();
				this._EstatusPM = value;
				this.SendPropertyChanged("EstatusPM");
				this.OnEstatusPMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Int")]
	public System.Nullable<int> IDR
	{
		get
		{
			return this._IDR;
		}
		set
		{
			if ((this._IDR != value))
			{
				this.OnIDRChanging(value);
				this.SendPropertyChanging();
				this._IDR = value;
				this.SendPropertyChanged("IDR");
				this.OnIDRChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class ObtenerMenuPuestoResult
{
	
	private System.Nullable<int> _IDPadreM;
	
	public ObtenerMenuPuestoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPadreM", DbType="Int")]
	public System.Nullable<int> IDPadreM
	{
		get
		{
			return this._IDPadreM;
		}
		set
		{
			if ((this._IDPadreM != value))
			{
				this._IDPadreM = value;
			}
		}
	}
}
#pragma warning restore 1591
