#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VSSECTEST")]
public partial class SECDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertRol(Rol instance);
  partial void UpdateRol(Rol instance);
  partial void DeleteRol(Rol instance);
  partial void InsertEncuesta(Encuesta instance);
  partial void UpdateEncuesta(Encuesta instance);
  partial void DeleteEncuesta(Encuesta instance);
  partial void InsertRespuesta(Respuesta instance);
  partial void UpdateRespuesta(Respuesta instance);
  partial void DeleteRespuesta(Respuesta instance);
  partial void InsertPregunta(Pregunta instance);
  partial void UpdatePregunta(Pregunta instance);
  partial void DeletePregunta(Pregunta instance);
  partial void InsertUnidad(Unidad instance);
  partial void UpdateUnidad(Unidad instance);
  partial void DeleteUnidad(Unidad instance);
  partial void InsertUsuarioUnidad(UsuarioUnidad instance);
  partial void UpdateUsuarioUnidad(UsuarioUnidad instance);
  partial void DeleteUsuarioUnidad(UsuarioUnidad instance);
  partial void InsertUsuario_Encuesta(Usuario_Encuesta instance);
  partial void UpdateUsuario_Encuesta(Usuario_Encuesta instance);
  partial void DeleteUsuario_Encuesta(Usuario_Encuesta instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  #endregion
	
	public SECDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VSSECTESTConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public SECDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SECDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SECDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public SECDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Rol> Rol
	{
		get
		{
			return this.GetTable<Rol>();
		}
	}
	
	public System.Data.Linq.Table<Encuesta> Encuesta
	{
		get
		{
			return this.GetTable<Encuesta>();
		}
	}
	
	public System.Data.Linq.Table<Respuesta> Respuesta
	{
		get
		{
			return this.GetTable<Respuesta>();
		}
	}
	
	public System.Data.Linq.Table<Pregunta> Pregunta
	{
		get
		{
			return this.GetTable<Pregunta>();
		}
	}
	
	public System.Data.Linq.Table<ObtenerDetalleEncuesta> ObtenerDetalleEncuesta
	{
		get
		{
			return this.GetTable<ObtenerDetalleEncuesta>();
		}
	}
	
	public System.Data.Linq.Table<Unidad> Unidad
	{
		get
		{
			return this.GetTable<Unidad>();
		}
	}
	
	public System.Data.Linq.Table<UsuarioUnidad> UsuarioUnidad
	{
		get
		{
			return this.GetTable<UsuarioUnidad>();
		}
	}
	
	public System.Data.Linq.Table<Usuario_Encuesta> Usuario_Encuesta
	{
		get
		{
			return this.GetTable<Usuario_Encuesta>();
		}
	}
	
	public System.Data.Linq.Table<ReporteConcentrado> ReporteConcentrado
	{
		get
		{
			return this.GetTable<ReporteConcentrado>();
		}
	}
	
	public System.Data.Linq.Table<ObtenerEvaluacionesUnidad> ObtenerEvaluacionesUnidad
	{
		get
		{
			return this.GetTable<ObtenerEvaluacionesUnidad>();
		}
	}
	
	public System.Data.Linq.Table<ObtenerPromedioUnidad> ObtenerPromedioUnidad
	{
		get
		{
			return this.GetTable<ObtenerPromedioUnidad>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
	
	public System.Data.Linq.Table<ObtenerInfoUsuario> ObtenerInfoUsuario
	{
		get
		{
			return this.GetTable<ObtenerInfoUsuario>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDR;
	
	private string _NombreR;
	
	private string _DescripcionR;
	
	private EntitySet<Usuario> _Usuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRChanging(int value);
    partial void OnIDRChanged();
    partial void OnNombreRChanging(string value);
    partial void OnNombreRChanged();
    partial void OnDescripcionRChanging(string value);
    partial void OnDescripcionRChanged();
    #endregion
	
	public Rol()
	{
		this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDR
	{
		get
		{
			return this._IDR;
		}
		set
		{
			if ((this._IDR != value))
			{
				this.OnIDRChanging(value);
				this.SendPropertyChanging();
				this._IDR = value;
				this.SendPropertyChanged("IDR");
				this.OnIDRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreR", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreR
	{
		get
		{
			return this._NombreR;
		}
		set
		{
			if ((this._NombreR != value))
			{
				this.OnNombreRChanging(value);
				this.SendPropertyChanging();
				this._NombreR = value;
				this.SendPropertyChanged("NombreR");
				this.OnNombreRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionR", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
	public string DescripcionR
	{
		get
		{
			return this._DescripcionR;
		}
		set
		{
			if ((this._DescripcionR != value))
			{
				this.OnDescripcionRChanging(value);
				this.SendPropertyChanging();
				this._DescripcionR = value;
				this.SendPropertyChanged("DescripcionR");
				this.OnDescripcionRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Usuario", ThisKey="IDR", OtherKey="IDR")]
	public EntitySet<Usuario> Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			this._Usuario.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Usuario(Usuario entity)
	{
		this.SendPropertyChanging();
		entity.Rol = this;
	}
	
	private void detach_Usuario(Usuario entity)
	{
		this.SendPropertyChanging();
		entity.Rol = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Encuesta")]
public partial class Encuesta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDE;
	
	private string _TipoE;
	
	private int _P1E;
	
	private int _P2E;
	
	private int _P3E;
	
	private int _P4E;
	
	private int _P5E;
	
	private EntitySet<Usuario_Encuesta> _Usuario_Encuesta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEChanging(int value);
    partial void OnIDEChanged();
    partial void OnTipoEChanging(string value);
    partial void OnTipoEChanged();
    partial void OnP1EChanging(int value);
    partial void OnP1EChanged();
    partial void OnP2EChanging(int value);
    partial void OnP2EChanged();
    partial void OnP3EChanging(int value);
    partial void OnP3EChanged();
    partial void OnP4EChanging(int value);
    partial void OnP4EChanged();
    partial void OnP5EChanging(int value);
    partial void OnP5EChanged();
    #endregion
	
	public Encuesta()
	{
		this._Usuario_Encuesta = new EntitySet<Usuario_Encuesta>(new Action<Usuario_Encuesta>(this.attach_Usuario_Encuesta), new Action<Usuario_Encuesta>(this.detach_Usuario_Encuesta));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDE
	{
		get
		{
			return this._IDE;
		}
		set
		{
			if ((this._IDE != value))
			{
				this.OnIDEChanging(value);
				this.SendPropertyChanging();
				this._IDE = value;
				this.SendPropertyChanged("IDE");
				this.OnIDEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoE", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
	public string TipoE
	{
		get
		{
			return this._TipoE;
		}
		set
		{
			if ((this._TipoE != value))
			{
				this.OnTipoEChanging(value);
				this.SendPropertyChanging();
				this._TipoE = value;
				this.SendPropertyChanged("TipoE");
				this.OnTipoEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P1E", DbType="Int NOT NULL")]
	public int P1E
	{
		get
		{
			return this._P1E;
		}
		set
		{
			if ((this._P1E != value))
			{
				this.OnP1EChanging(value);
				this.SendPropertyChanging();
				this._P1E = value;
				this.SendPropertyChanged("P1E");
				this.OnP1EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P2E", DbType="Int NOT NULL")]
	public int P2E
	{
		get
		{
			return this._P2E;
		}
		set
		{
			if ((this._P2E != value))
			{
				this.OnP2EChanging(value);
				this.SendPropertyChanging();
				this._P2E = value;
				this.SendPropertyChanged("P2E");
				this.OnP2EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P3E", DbType="Int NOT NULL")]
	public int P3E
	{
		get
		{
			return this._P3E;
		}
		set
		{
			if ((this._P3E != value))
			{
				this.OnP3EChanging(value);
				this.SendPropertyChanging();
				this._P3E = value;
				this.SendPropertyChanged("P3E");
				this.OnP3EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P4E", DbType="Int NOT NULL")]
	public int P4E
	{
		get
		{
			return this._P4E;
		}
		set
		{
			if ((this._P4E != value))
			{
				this.OnP4EChanging(value);
				this.SendPropertyChanging();
				this._P4E = value;
				this.SendPropertyChanged("P4E");
				this.OnP4EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P5E", DbType="Int NOT NULL")]
	public int P5E
	{
		get
		{
			return this._P5E;
		}
		set
		{
			if ((this._P5E != value))
			{
				this.OnP5EChanging(value);
				this.SendPropertyChanging();
				this._P5E = value;
				this.SendPropertyChanged("P5E");
				this.OnP5EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encuesta_Usuario_Encuesta", Storage="_Usuario_Encuesta", ThisKey="IDE", OtherKey="IDE")]
	public EntitySet<Usuario_Encuesta> Usuario_Encuesta
	{
		get
		{
			return this._Usuario_Encuesta;
		}
		set
		{
			this._Usuario_Encuesta.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Usuario_Encuesta(Usuario_Encuesta entity)
	{
		this.SendPropertyChanging();
		entity.Encuesta = this;
	}
	
	private void detach_Usuario_Encuesta(Usuario_Encuesta entity)
	{
		this.SendPropertyChanging();
		entity.Encuesta = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Respuesta")]
public partial class Respuesta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDRE;
	
	private short _R1RE;
	
	private short _R2RE;
	
	private short _R3RE;
	
	private short _R4RE;
	
	private short _R5RE;
	
	private EntitySet<Usuario_Encuesta> _Usuario_Encuesta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDREChanging(int value);
    partial void OnIDREChanged();
    partial void OnR1REChanging(short value);
    partial void OnR1REChanged();
    partial void OnR2REChanging(short value);
    partial void OnR2REChanged();
    partial void OnR3REChanging(short value);
    partial void OnR3REChanged();
    partial void OnR4REChanging(short value);
    partial void OnR4REChanged();
    partial void OnR5REChanging(short value);
    partial void OnR5REChanged();
    #endregion
	
	public Respuesta()
	{
		this._Usuario_Encuesta = new EntitySet<Usuario_Encuesta>(new Action<Usuario_Encuesta>(this.attach_Usuario_Encuesta), new Action<Usuario_Encuesta>(this.detach_Usuario_Encuesta));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDRE
	{
		get
		{
			return this._IDRE;
		}
		set
		{
			if ((this._IDRE != value))
			{
				this.OnIDREChanging(value);
				this.SendPropertyChanging();
				this._IDRE = value;
				this.SendPropertyChanged("IDRE");
				this.OnIDREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R1RE", DbType="SmallInt NOT NULL")]
	public short R1RE
	{
		get
		{
			return this._R1RE;
		}
		set
		{
			if ((this._R1RE != value))
			{
				this.OnR1REChanging(value);
				this.SendPropertyChanging();
				this._R1RE = value;
				this.SendPropertyChanged("R1RE");
				this.OnR1REChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R2RE", DbType="SmallInt NOT NULL")]
	public short R2RE
	{
		get
		{
			return this._R2RE;
		}
		set
		{
			if ((this._R2RE != value))
			{
				this.OnR2REChanging(value);
				this.SendPropertyChanging();
				this._R2RE = value;
				this.SendPropertyChanged("R2RE");
				this.OnR2REChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R3RE", DbType="SmallInt NOT NULL")]
	public short R3RE
	{
		get
		{
			return this._R3RE;
		}
		set
		{
			if ((this._R3RE != value))
			{
				this.OnR3REChanging(value);
				this.SendPropertyChanging();
				this._R3RE = value;
				this.SendPropertyChanged("R3RE");
				this.OnR3REChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R4RE", DbType="SmallInt NOT NULL")]
	public short R4RE
	{
		get
		{
			return this._R4RE;
		}
		set
		{
			if ((this._R4RE != value))
			{
				this.OnR4REChanging(value);
				this.SendPropertyChanging();
				this._R4RE = value;
				this.SendPropertyChanged("R4RE");
				this.OnR4REChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R5RE", DbType="SmallInt NOT NULL")]
	public short R5RE
	{
		get
		{
			return this._R5RE;
		}
		set
		{
			if ((this._R5RE != value))
			{
				this.OnR5REChanging(value);
				this.SendPropertyChanging();
				this._R5RE = value;
				this.SendPropertyChanged("R5RE");
				this.OnR5REChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Respuesta_Usuario_Encuesta", Storage="_Usuario_Encuesta", ThisKey="IDRE", OtherKey="IDRE")]
	public EntitySet<Usuario_Encuesta> Usuario_Encuesta
	{
		get
		{
			return this._Usuario_Encuesta;
		}
		set
		{
			this._Usuario_Encuesta.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Usuario_Encuesta(Usuario_Encuesta entity)
	{
		this.SendPropertyChanging();
		entity.Respuesta = this;
	}
	
	private void detach_Usuario_Encuesta(Usuario_Encuesta entity)
	{
		this.SendPropertyChanging();
		entity.Respuesta = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pregunta")]
public partial class Pregunta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDP;
	
	private string _PreguntaP;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPChanging(int value);
    partial void OnIDPChanged();
    partial void OnPreguntaPChanging(string value);
    partial void OnPreguntaPChanged();
    #endregion
	
	public Pregunta()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDP
	{
		get
		{
			return this._IDP;
		}
		set
		{
			if ((this._IDP != value))
			{
				this.OnIDPChanging(value);
				this.SendPropertyChanging();
				this._IDP = value;
				this.SendPropertyChanged("IDP");
				this.OnIDPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreguntaP", DbType="VarChar(600) NOT NULL", CanBeNull=false)]
	public string PreguntaP
	{
		get
		{
			return this._PreguntaP;
		}
		set
		{
			if ((this._PreguntaP != value))
			{
				this.OnPreguntaPChanging(value);
				this.SendPropertyChanging();
				this._PreguntaP = value;
				this.SendPropertyChanged("PreguntaP");
				this.OnPreguntaPChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObtenerDetalleEncuesta")]
public partial class ObtenerDetalleEncuesta
{
	
	private int _IDU_E;
	
	private System.Nullable<int> _IDU;
	
	private System.Nullable<int> _IDE;
	
	private System.Nullable<int> _IDRE;
	
	private System.Nullable<int> _EvaluandoU_E;
	
	private System.Nullable<System.DateTime> _FechaAplicacionU_E;
	
	private string _TipoE;
	
	private short _R1RE;
	
	private short _R2RE;
	
	private short _R3RE;
	
	private short _R4RE;
	
	private short _R5RE;
	
	public ObtenerDetalleEncuesta()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU_E", DbType="Int NOT NULL")]
	public int IDU_E
	{
		get
		{
			return this._IDU_E;
		}
		set
		{
			if ((this._IDU_E != value))
			{
				this._IDU_E = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", DbType="Int")]
	public System.Nullable<int> IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this._IDU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDE", DbType="Int")]
	public System.Nullable<int> IDE
	{
		get
		{
			return this._IDE;
		}
		set
		{
			if ((this._IDE != value))
			{
				this._IDE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRE", DbType="Int")]
	public System.Nullable<int> IDRE
	{
		get
		{
			return this._IDRE;
		}
		set
		{
			if ((this._IDRE != value))
			{
				this._IDRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluandoU_E", DbType="Int")]
	public System.Nullable<int> EvaluandoU_E
	{
		get
		{
			return this._EvaluandoU_E;
		}
		set
		{
			if ((this._EvaluandoU_E != value))
			{
				this._EvaluandoU_E = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionU_E", DbType="Date")]
	public System.Nullable<System.DateTime> FechaAplicacionU_E
	{
		get
		{
			return this._FechaAplicacionU_E;
		}
		set
		{
			if ((this._FechaAplicacionU_E != value))
			{
				this._FechaAplicacionU_E = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoE", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
	public string TipoE
	{
		get
		{
			return this._TipoE;
		}
		set
		{
			if ((this._TipoE != value))
			{
				this._TipoE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R1RE", DbType="SmallInt NOT NULL")]
	public short R1RE
	{
		get
		{
			return this._R1RE;
		}
		set
		{
			if ((this._R1RE != value))
			{
				this._R1RE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R2RE", DbType="SmallInt NOT NULL")]
	public short R2RE
	{
		get
		{
			return this._R2RE;
		}
		set
		{
			if ((this._R2RE != value))
			{
				this._R2RE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R3RE", DbType="SmallInt NOT NULL")]
	public short R3RE
	{
		get
		{
			return this._R3RE;
		}
		set
		{
			if ((this._R3RE != value))
			{
				this._R3RE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R4RE", DbType="SmallInt NOT NULL")]
	public short R4RE
	{
		get
		{
			return this._R4RE;
		}
		set
		{
			if ((this._R4RE != value))
			{
				this._R4RE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R5RE", DbType="SmallInt NOT NULL")]
	public short R5RE
	{
		get
		{
			return this._R5RE;
		}
		set
		{
			if ((this._R5RE != value))
			{
				this._R5RE = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Unidad")]
public partial class Unidad : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDUN;
	
	private string _NombreUN;
	
	private string _RazonSocialUN;
	
	private int _IDHumanSiteUN;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUNChanging(int value);
    partial void OnIDUNChanged();
    partial void OnNombreUNChanging(string value);
    partial void OnNombreUNChanged();
    partial void OnRazonSocialUNChanging(string value);
    partial void OnRazonSocialUNChanged();
    partial void OnIDHumanSiteUNChanging(int value);
    partial void OnIDHumanSiteUNChanged();
    #endregion
	
	public Unidad()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this.OnIDUNChanging(value);
				this.SendPropertyChanging();
				this._IDUN = value;
				this.SendPropertyChanged("IDUN");
				this.OnIDUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this.OnNombreUNChanging(value);
				this.SendPropertyChanging();
				this._NombreUN = value;
				this.SendPropertyChanged("NombreUN");
				this.OnNombreUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocialUN", DbType="VarChar(600) NOT NULL", CanBeNull=false)]
	public string RazonSocialUN
	{
		get
		{
			return this._RazonSocialUN;
		}
		set
		{
			if ((this._RazonSocialUN != value))
			{
				this.OnRazonSocialUNChanging(value);
				this.SendPropertyChanging();
				this._RazonSocialUN = value;
				this.SendPropertyChanged("RazonSocialUN");
				this.OnRazonSocialUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHumanSiteUN", DbType="Int NOT NULL")]
	public int IDHumanSiteUN
	{
		get
		{
			return this._IDHumanSiteUN;
		}
		set
		{
			if ((this._IDHumanSiteUN != value))
			{
				this.OnIDHumanSiteUNChanging(value);
				this.SendPropertyChanging();
				this._IDHumanSiteUN = value;
				this.SendPropertyChanged("IDHumanSiteUN");
				this.OnIDHumanSiteUNChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioUnidad")]
public partial class UsuarioUnidad : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDUU;
	
	private System.Nullable<int> _IDU;
	
	private System.Nullable<int> _NumeroEmpleadoUU;
	
	private System.Nullable<int> _IDUN;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUUChanging(int value);
    partial void OnIDUUChanged();
    partial void OnIDUChanging(System.Nullable<int> value);
    partial void OnIDUChanged();
    partial void OnNumeroEmpleadoUUChanging(System.Nullable<int> value);
    partial void OnNumeroEmpleadoUUChanged();
    partial void OnIDUNChanging(System.Nullable<int> value);
    partial void OnIDUNChanged();
    #endregion
	
	public UsuarioUnidad()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDUU
	{
		get
		{
			return this._IDUU;
		}
		set
		{
			if ((this._IDUU != value))
			{
				this.OnIDUUChanging(value);
				this.SendPropertyChanging();
				this._IDUU = value;
				this.SendPropertyChanged("IDUU");
				this.OnIDUUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", DbType="Int")]
	public System.Nullable<int> IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroEmpleadoUU", DbType="Int")]
	public System.Nullable<int> NumeroEmpleadoUU
	{
		get
		{
			return this._NumeroEmpleadoUU;
		}
		set
		{
			if ((this._NumeroEmpleadoUU != value))
			{
				this.OnNumeroEmpleadoUUChanging(value);
				this.SendPropertyChanging();
				this._NumeroEmpleadoUU = value;
				this.SendPropertyChanged("NumeroEmpleadoUU");
				this.OnNumeroEmpleadoUUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", DbType="Int")]
	public System.Nullable<int> IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this.OnIDUNChanging(value);
				this.SendPropertyChanging();
				this._IDUN = value;
				this.SendPropertyChanged("IDUN");
				this.OnIDUNChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario_Encuesta")]
public partial class Usuario_Encuesta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDU_E;
	
	private System.Nullable<int> _IDU;
	
	private System.Nullable<int> _IDE;
	
	private System.Nullable<int> _IDRE;
	
	private System.Nullable<int> _EvaluandoU_E;
	
	private System.Nullable<System.DateTime> _FechaAplicacionU_E;
	
	private EntityRef<Encuesta> _Encuesta;
	
	private EntityRef<Respuesta> _Respuesta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDU_EChanging(int value);
    partial void OnIDU_EChanged();
    partial void OnIDUChanging(System.Nullable<int> value);
    partial void OnIDUChanged();
    partial void OnIDEChanging(System.Nullable<int> value);
    partial void OnIDEChanged();
    partial void OnIDREChanging(System.Nullable<int> value);
    partial void OnIDREChanged();
    partial void OnEvaluandoU_EChanging(System.Nullable<int> value);
    partial void OnEvaluandoU_EChanged();
    partial void OnFechaAplicacionU_EChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAplicacionU_EChanged();
    #endregion
	
	public Usuario_Encuesta()
	{
		this._Encuesta = default(EntityRef<Encuesta>);
		this._Respuesta = default(EntityRef<Respuesta>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU_E", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDU_E
	{
		get
		{
			return this._IDU_E;
		}
		set
		{
			if ((this._IDU_E != value))
			{
				this.OnIDU_EChanging(value);
				this.SendPropertyChanging();
				this._IDU_E = value;
				this.SendPropertyChanged("IDU_E");
				this.OnIDU_EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", DbType="Int")]
	public System.Nullable<int> IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDE", DbType="Int")]
	public System.Nullable<int> IDE
	{
		get
		{
			return this._IDE;
		}
		set
		{
			if ((this._IDE != value))
			{
				if (this._Encuesta.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDEChanging(value);
				this.SendPropertyChanging();
				this._IDE = value;
				this.SendPropertyChanged("IDE");
				this.OnIDEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRE", DbType="Int")]
	public System.Nullable<int> IDRE
	{
		get
		{
			return this._IDRE;
		}
		set
		{
			if ((this._IDRE != value))
			{
				if (this._Respuesta.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDREChanging(value);
				this.SendPropertyChanging();
				this._IDRE = value;
				this.SendPropertyChanged("IDRE");
				this.OnIDREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvaluandoU_E", DbType="Int")]
	public System.Nullable<int> EvaluandoU_E
	{
		get
		{
			return this._EvaluandoU_E;
		}
		set
		{
			if ((this._EvaluandoU_E != value))
			{
				this.OnEvaluandoU_EChanging(value);
				this.SendPropertyChanging();
				this._EvaluandoU_E = value;
				this.SendPropertyChanged("EvaluandoU_E");
				this.OnEvaluandoU_EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionU_E", DbType="Date")]
	public System.Nullable<System.DateTime> FechaAplicacionU_E
	{
		get
		{
			return this._FechaAplicacionU_E;
		}
		set
		{
			if ((this._FechaAplicacionU_E != value))
			{
				this.OnFechaAplicacionU_EChanging(value);
				this.SendPropertyChanging();
				this._FechaAplicacionU_E = value;
				this.SendPropertyChanged("FechaAplicacionU_E");
				this.OnFechaAplicacionU_EChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encuesta_Usuario_Encuesta", Storage="_Encuesta", ThisKey="IDE", OtherKey="IDE", IsForeignKey=true, DeleteRule="CASCADE")]
	public Encuesta Encuesta
	{
		get
		{
			return this._Encuesta.Entity;
		}
		set
		{
			Encuesta previousValue = this._Encuesta.Entity;
			if (((previousValue != value) 
						|| (this._Encuesta.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Encuesta.Entity = null;
					previousValue.Usuario_Encuesta.Remove(this);
				}
				this._Encuesta.Entity = value;
				if ((value != null))
				{
					value.Usuario_Encuesta.Add(this);
					this._IDE = value.IDE;
				}
				else
				{
					this._IDE = default(Nullable<int>);
				}
				this.SendPropertyChanged("Encuesta");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Respuesta_Usuario_Encuesta", Storage="_Respuesta", ThisKey="IDRE", OtherKey="IDRE", IsForeignKey=true, DeleteRule="CASCADE")]
	public Respuesta Respuesta
	{
		get
		{
			return this._Respuesta.Entity;
		}
		set
		{
			Respuesta previousValue = this._Respuesta.Entity;
			if (((previousValue != value) 
						|| (this._Respuesta.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Respuesta.Entity = null;
					previousValue.Usuario_Encuesta.Remove(this);
				}
				this._Respuesta.Entity = value;
				if ((value != null))
				{
					value.Usuario_Encuesta.Add(this);
					this._IDRE = value.IDRE;
				}
				else
				{
					this._IDRE = default(Nullable<int>);
				}
				this.SendPropertyChanged("Respuesta");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteConcentrado")]
public partial class ReporteConcentrado
{
	
	private System.Nullable<int> _NoEvaluaciones;
	
	private System.Nullable<int> _Evaluado;
	
	private System.Nullable<int> _Evaluador;
	
	private string _UnidadEvaluado;
	
	private string _UnidadEvaluador;
	
	private string _TipoE;
	
	private int _IDE;
	
	private System.Nullable<System.DateTime> _FechaAplicacionU_E;
	
	private int _IDHumanSiteUN;
	
	public ReporteConcentrado()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoEvaluaciones", DbType="Int")]
	public System.Nullable<int> NoEvaluaciones
	{
		get
		{
			return this._NoEvaluaciones;
		}
		set
		{
			if ((this._NoEvaluaciones != value))
			{
				this._NoEvaluaciones = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evaluado", DbType="Int")]
	public System.Nullable<int> Evaluado
	{
		get
		{
			return this._Evaluado;
		}
		set
		{
			if ((this._Evaluado != value))
			{
				this._Evaluado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evaluador", DbType="Int")]
	public System.Nullable<int> Evaluador
	{
		get
		{
			return this._Evaluador;
		}
		set
		{
			if ((this._Evaluador != value))
			{
				this._Evaluador = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadEvaluado", DbType="VarChar(600) NOT NULL", CanBeNull=false)]
	public string UnidadEvaluado
	{
		get
		{
			return this._UnidadEvaluado;
		}
		set
		{
			if ((this._UnidadEvaluado != value))
			{
				this._UnidadEvaluado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadEvaluador", DbType="VarChar(600) NOT NULL", CanBeNull=false)]
	public string UnidadEvaluador
	{
		get
		{
			return this._UnidadEvaluador;
		}
		set
		{
			if ((this._UnidadEvaluador != value))
			{
				this._UnidadEvaluador = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoE", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
	public string TipoE
	{
		get
		{
			return this._TipoE;
		}
		set
		{
			if ((this._TipoE != value))
			{
				this._TipoE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDE", DbType="Int NOT NULL")]
	public int IDE
	{
		get
		{
			return this._IDE;
		}
		set
		{
			if ((this._IDE != value))
			{
				this._IDE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionU_E", DbType="Date")]
	public System.Nullable<System.DateTime> FechaAplicacionU_E
	{
		get
		{
			return this._FechaAplicacionU_E;
		}
		set
		{
			if ((this._FechaAplicacionU_E != value))
			{
				this._FechaAplicacionU_E = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHumanSiteUN", DbType="Int NOT NULL")]
	public int IDHumanSiteUN
	{
		get
		{
			return this._IDHumanSiteUN;
		}
		set
		{
			if ((this._IDHumanSiteUN != value))
			{
				this._IDHumanSiteUN = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObtenerEvaluacionesUnidad")]
public partial class ObtenerEvaluacionesUnidad
{
	
	private System.Nullable<int> _NoEvaluaciones;
	
	private string _NombreUN;
	
	private System.Nullable<System.DateTime> _FechaAplicacionU_E;
	
	public ObtenerEvaluacionesUnidad()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoEvaluaciones", DbType="Int")]
	public System.Nullable<int> NoEvaluaciones
	{
		get
		{
			return this._NoEvaluaciones;
		}
		set
		{
			if ((this._NoEvaluaciones != value))
			{
				this._NoEvaluaciones = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this._NombreUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionU_E", DbType="Date")]
	public System.Nullable<System.DateTime> FechaAplicacionU_E
	{
		get
		{
			return this._FechaAplicacionU_E;
		}
		set
		{
			if ((this._FechaAplicacionU_E != value))
			{
				this._FechaAplicacionU_E = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObtenerPromedioUnidad")]
public partial class ObtenerPromedioUnidad
{
	
	private string _NombreUN;
	
	private System.Nullable<System.DateTime> _FechaAplicacionU_E;
	
	private System.Nullable<int> _PR1;
	
	private System.Nullable<int> _PR2;
	
	private System.Nullable<int> _PR3;
	
	private System.Nullable<int> _PR4;
	
	private System.Nullable<int> _PR5;
	
	public ObtenerPromedioUnidad()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this._NombreUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionU_E", DbType="Date")]
	public System.Nullable<System.DateTime> FechaAplicacionU_E
	{
		get
		{
			return this._FechaAplicacionU_E;
		}
		set
		{
			if ((this._FechaAplicacionU_E != value))
			{
				this._FechaAplicacionU_E = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR1", DbType="Int")]
	public System.Nullable<int> PR1
	{
		get
		{
			return this._PR1;
		}
		set
		{
			if ((this._PR1 != value))
			{
				this._PR1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR2", DbType="Int")]
	public System.Nullable<int> PR2
	{
		get
		{
			return this._PR2;
		}
		set
		{
			if ((this._PR2 != value))
			{
				this._PR2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR3", DbType="Int")]
	public System.Nullable<int> PR3
	{
		get
		{
			return this._PR3;
		}
		set
		{
			if ((this._PR3 != value))
			{
				this._PR3 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR4", DbType="Int")]
	public System.Nullable<int> PR4
	{
		get
		{
			return this._PR4;
		}
		set
		{
			if ((this._PR4 != value))
			{
				this._PR4 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR5", DbType="Int")]
	public System.Nullable<int> PR5
	{
		get
		{
			return this._PR5;
		}
		set
		{
			if ((this._PR5 != value))
			{
				this._PR5 = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDU;
	
	private System.Nullable<int> _IDR;
	
	private int _NumeroEmpleadoU;
	
	private bool _EstatusU;
	
	private string _PINU;
	
	private System.Nullable<bool> _EspCocinaU;
	
	private System.Nullable<bool> _EspPisoU;
	
	private System.Nullable<bool> _EspPanaderiaU;
	
	private System.Nullable<bool> _EspAlmacenU;
	
	private System.Nullable<System.DateTime> _FechaAcreditacionU;
	
	private string _ObservacionesAcreditacionU;
	
	private System.Nullable<int> _IDUNHumanSite;
	
	private System.Nullable<int> _DiasCapacitacionU;
	
	private EntityRef<Rol> _Rol;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUChanging(int value);
    partial void OnIDUChanged();
    partial void OnIDRChanging(System.Nullable<int> value);
    partial void OnIDRChanged();
    partial void OnNumeroEmpleadoUChanging(int value);
    partial void OnNumeroEmpleadoUChanged();
    partial void OnEstatusUChanging(bool value);
    partial void OnEstatusUChanged();
    partial void OnPINUChanging(string value);
    partial void OnPINUChanged();
    partial void OnEspCocinaUChanging(System.Nullable<bool> value);
    partial void OnEspCocinaUChanged();
    partial void OnEspPisoUChanging(System.Nullable<bool> value);
    partial void OnEspPisoUChanged();
    partial void OnEspPanaderiaUChanging(System.Nullable<bool> value);
    partial void OnEspPanaderiaUChanged();
    partial void OnEspAlmacenUChanging(System.Nullable<bool> value);
    partial void OnEspAlmacenUChanged();
    partial void OnFechaAcreditacionUChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAcreditacionUChanged();
    partial void OnObservacionesAcreditacionUChanging(string value);
    partial void OnObservacionesAcreditacionUChanged();
    partial void OnIDUNHumanSiteChanging(System.Nullable<int> value);
    partial void OnIDUNHumanSiteChanged();
    partial void OnDiasCapacitacionUChanging(System.Nullable<int> value);
    partial void OnDiasCapacitacionUChanged();
    #endregion
	
	public Usuario()
	{
		this._Rol = default(EntityRef<Rol>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Int")]
	public System.Nullable<int> IDR
	{
		get
		{
			return this._IDR;
		}
		set
		{
			if ((this._IDR != value))
			{
				if (this._Rol.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDRChanging(value);
				this.SendPropertyChanging();
				this._IDR = value;
				this.SendPropertyChanged("IDR");
				this.OnIDRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroEmpleadoU", DbType="Int NOT NULL")]
	public int NumeroEmpleadoU
	{
		get
		{
			return this._NumeroEmpleadoU;
		}
		set
		{
			if ((this._NumeroEmpleadoU != value))
			{
				this.OnNumeroEmpleadoUChanging(value);
				this.SendPropertyChanging();
				this._NumeroEmpleadoU = value;
				this.SendPropertyChanged("NumeroEmpleadoU");
				this.OnNumeroEmpleadoUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusU", DbType="Bit NOT NULL")]
	public bool EstatusU
	{
		get
		{
			return this._EstatusU;
		}
		set
		{
			if ((this._EstatusU != value))
			{
				this.OnEstatusUChanging(value);
				this.SendPropertyChanging();
				this._EstatusU = value;
				this.SendPropertyChanged("EstatusU");
				this.OnEstatusUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PINU", DbType="Char(4)")]
	public string PINU
	{
		get
		{
			return this._PINU;
		}
		set
		{
			if ((this._PINU != value))
			{
				this.OnPINUChanging(value);
				this.SendPropertyChanging();
				this._PINU = value;
				this.SendPropertyChanged("PINU");
				this.OnPINUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspCocinaU", DbType="Bit")]
	public System.Nullable<bool> EspCocinaU
	{
		get
		{
			return this._EspCocinaU;
		}
		set
		{
			if ((this._EspCocinaU != value))
			{
				this.OnEspCocinaUChanging(value);
				this.SendPropertyChanging();
				this._EspCocinaU = value;
				this.SendPropertyChanged("EspCocinaU");
				this.OnEspCocinaUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspPisoU", DbType="Bit")]
	public System.Nullable<bool> EspPisoU
	{
		get
		{
			return this._EspPisoU;
		}
		set
		{
			if ((this._EspPisoU != value))
			{
				this.OnEspPisoUChanging(value);
				this.SendPropertyChanging();
				this._EspPisoU = value;
				this.SendPropertyChanged("EspPisoU");
				this.OnEspPisoUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspPanaderiaU", DbType="Bit")]
	public System.Nullable<bool> EspPanaderiaU
	{
		get
		{
			return this._EspPanaderiaU;
		}
		set
		{
			if ((this._EspPanaderiaU != value))
			{
				this.OnEspPanaderiaUChanging(value);
				this.SendPropertyChanging();
				this._EspPanaderiaU = value;
				this.SendPropertyChanged("EspPanaderiaU");
				this.OnEspPanaderiaUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspAlmacenU", DbType="Bit")]
	public System.Nullable<bool> EspAlmacenU
	{
		get
		{
			return this._EspAlmacenU;
		}
		set
		{
			if ((this._EspAlmacenU != value))
			{
				this.OnEspAlmacenUChanging(value);
				this.SendPropertyChanging();
				this._EspAlmacenU = value;
				this.SendPropertyChanged("EspAlmacenU");
				this.OnEspAlmacenUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAcreditacionU", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaAcreditacionU
	{
		get
		{
			return this._FechaAcreditacionU;
		}
		set
		{
			if ((this._FechaAcreditacionU != value))
			{
				this.OnFechaAcreditacionUChanging(value);
				this.SendPropertyChanging();
				this._FechaAcreditacionU = value;
				this.SendPropertyChanged("FechaAcreditacionU");
				this.OnFechaAcreditacionUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObservacionesAcreditacionU", DbType="VarChar(300)")]
	public string ObservacionesAcreditacionU
	{
		get
		{
			return this._ObservacionesAcreditacionU;
		}
		set
		{
			if ((this._ObservacionesAcreditacionU != value))
			{
				this.OnObservacionesAcreditacionUChanging(value);
				this.SendPropertyChanging();
				this._ObservacionesAcreditacionU = value;
				this.SendPropertyChanged("ObservacionesAcreditacionU");
				this.OnObservacionesAcreditacionUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNHumanSite", DbType="Int")]
	public System.Nullable<int> IDUNHumanSite
	{
		get
		{
			return this._IDUNHumanSite;
		}
		set
		{
			if ((this._IDUNHumanSite != value))
			{
				this.OnIDUNHumanSiteChanging(value);
				this.SendPropertyChanging();
				this._IDUNHumanSite = value;
				this.SendPropertyChanged("IDUNHumanSite");
				this.OnIDUNHumanSiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasCapacitacionU", DbType="Int")]
	public System.Nullable<int> DiasCapacitacionU
	{
		get
		{
			return this._DiasCapacitacionU;
		}
		set
		{
			if ((this._DiasCapacitacionU != value))
			{
				this.OnDiasCapacitacionUChanging(value);
				this.SendPropertyChanging();
				this._DiasCapacitacionU = value;
				this.SendPropertyChanged("DiasCapacitacionU");
				this.OnDiasCapacitacionUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Usuario", Storage="_Rol", ThisKey="IDR", OtherKey="IDR", IsForeignKey=true, DeleteRule="CASCADE")]
	public Rol Rol
	{
		get
		{
			return this._Rol.Entity;
		}
		set
		{
			Rol previousValue = this._Rol.Entity;
			if (((previousValue != value) 
						|| (this._Rol.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rol.Entity = null;
					previousValue.Usuario.Remove(this);
				}
				this._Rol.Entity = value;
				if ((value != null))
				{
					value.Usuario.Add(this);
					this._IDR = value.IDR;
				}
				else
				{
					this._IDR = default(Nullable<int>);
				}
				this.SendPropertyChanged("Rol");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObtenerInfoUsuario")]
public partial class ObtenerInfoUsuario
{
	
	private int _IDU;
	
	private System.Nullable<int> _IDR;
	
	private int _NumeroEmpleadoU;
	
	private bool _EstatusU;
	
	private string _PINU;
	
	private System.Nullable<bool> _EspCocinaU;
	
	private System.Nullable<bool> _EspPisoU;
	
	private System.Nullable<bool> _EspPanaderiaU;
	
	private System.Nullable<bool> _EspAlmacenU;
	
	private System.Nullable<System.DateTime> _FechaAcreditacionU;
	
	private string _ObservacionesAcreditacionU;
	
	private System.Nullable<int> _IDUNHumanSite;
	
	private System.Nullable<int> _DiasCapacitacionU;
	
	private string _NombreUN;
	
	private string _RazonSocialUN;
	
	private string _NombreR;
	
	public ObtenerInfoUsuario()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", DbType="Int NOT NULL")]
	public int IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this._IDU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Int")]
	public System.Nullable<int> IDR
	{
		get
		{
			return this._IDR;
		}
		set
		{
			if ((this._IDR != value))
			{
				this._IDR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroEmpleadoU", DbType="Int NOT NULL")]
	public int NumeroEmpleadoU
	{
		get
		{
			return this._NumeroEmpleadoU;
		}
		set
		{
			if ((this._NumeroEmpleadoU != value))
			{
				this._NumeroEmpleadoU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstatusU", DbType="Bit NOT NULL")]
	public bool EstatusU
	{
		get
		{
			return this._EstatusU;
		}
		set
		{
			if ((this._EstatusU != value))
			{
				this._EstatusU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PINU", DbType="Char(4)")]
	public string PINU
	{
		get
		{
			return this._PINU;
		}
		set
		{
			if ((this._PINU != value))
			{
				this._PINU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspCocinaU", DbType="Bit")]
	public System.Nullable<bool> EspCocinaU
	{
		get
		{
			return this._EspCocinaU;
		}
		set
		{
			if ((this._EspCocinaU != value))
			{
				this._EspCocinaU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspPisoU", DbType="Bit")]
	public System.Nullable<bool> EspPisoU
	{
		get
		{
			return this._EspPisoU;
		}
		set
		{
			if ((this._EspPisoU != value))
			{
				this._EspPisoU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspPanaderiaU", DbType="Bit")]
	public System.Nullable<bool> EspPanaderiaU
	{
		get
		{
			return this._EspPanaderiaU;
		}
		set
		{
			if ((this._EspPanaderiaU != value))
			{
				this._EspPanaderiaU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EspAlmacenU", DbType="Bit")]
	public System.Nullable<bool> EspAlmacenU
	{
		get
		{
			return this._EspAlmacenU;
		}
		set
		{
			if ((this._EspAlmacenU != value))
			{
				this._EspAlmacenU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAcreditacionU", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaAcreditacionU
	{
		get
		{
			return this._FechaAcreditacionU;
		}
		set
		{
			if ((this._FechaAcreditacionU != value))
			{
				this._FechaAcreditacionU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObservacionesAcreditacionU", DbType="VarChar(300)")]
	public string ObservacionesAcreditacionU
	{
		get
		{
			return this._ObservacionesAcreditacionU;
		}
		set
		{
			if ((this._ObservacionesAcreditacionU != value))
			{
				this._ObservacionesAcreditacionU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNHumanSite", DbType="Int")]
	public System.Nullable<int> IDUNHumanSite
	{
		get
		{
			return this._IDUNHumanSite;
		}
		set
		{
			if ((this._IDUNHumanSite != value))
			{
				this._IDUNHumanSite = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasCapacitacionU", DbType="Int")]
	public System.Nullable<int> DiasCapacitacionU
	{
		get
		{
			return this._DiasCapacitacionU;
		}
		set
		{
			if ((this._DiasCapacitacionU != value))
			{
				this._DiasCapacitacionU = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this._NombreUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocialUN", DbType="VarChar(600) NOT NULL", CanBeNull=false)]
	public string RazonSocialUN
	{
		get
		{
			return this._RazonSocialUN;
		}
		set
		{
			if ((this._RazonSocialUN != value))
			{
				this._RazonSocialUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreR", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
	public string NombreR
	{
		get
		{
			return this._NombreR;
		}
		set
		{
			if ((this._NombreR != value))
			{
				this._NombreR = value;
			}
		}
	}
}
#pragma warning restore 1591
