#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VSEITEST")]
public partial class REIDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertUnidad(Unidad instance);
  partial void UpdateUnidad(Unidad instance);
  partial void DeleteUnidad(Unidad instance);
  partial void InsertUsuario(Usuario instance);
  partial void UpdateUsuario(Usuario instance);
  partial void DeleteUsuario(Usuario instance);
  partial void InsertDocumento(Documento instance);
  partial void UpdateDocumento(Documento instance);
  partial void DeleteDocumento(Documento instance);
  partial void InsertVariacion(Variacion instance);
  partial void UpdateVariacion(Variacion instance);
  partial void DeleteVariacion(Variacion instance);
  partial void InsertInventario(Inventario instance);
  partial void UpdateInventario(Inventario instance);
  partial void DeleteInventario(Inventario instance);
  #endregion
	
	public REIDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VSEITESTConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public REIDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public REIDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public REIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public REIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Unidad> Unidad
	{
		get
		{
			return this.GetTable<Unidad>();
		}
	}
	
	public System.Data.Linq.Table<Usuario> Usuario
	{
		get
		{
			return this.GetTable<Usuario>();
		}
	}
	
	public System.Data.Linq.Table<Documento> Documento
	{
		get
		{
			return this.GetTable<Documento>();
		}
	}
	
	public System.Data.Linq.Table<Variacion> Variacion
	{
		get
		{
			return this.GetTable<Variacion>();
		}
	}
	
	public System.Data.Linq.Table<Inventario> Inventario
	{
		get
		{
			return this.GetTable<Inventario>();
		}
	}
	
	public System.Data.Linq.Table<ReporteInsumos> ReporteInsumos
	{
		get
		{
			return this.GetTable<ReporteInsumos>();
		}
	}
	
	public System.Data.Linq.Table<InventarioDocumento> InventarioDocumento
	{
		get
		{
			return this.GetTable<InventarioDocumento>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerDatosInsumoUnidad")]
	public ISingleResult<ObtenerDatosInsumoUnidadResult> ObtenerDatosInsumoUnidad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Insumo", DbType="VarChar(600)")] string insumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaIni", DbType="Date")] System.Nullable<System.DateTime> fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFin", DbType="Date")] System.Nullable<System.DateTime> fechaFin)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), insumo, fechaIni, fechaFin);
		return ((ISingleResult<ObtenerDatosInsumoUnidadResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerDatosInsumoUnidadArea")]
	public ISingleResult<ObtenerDatosInsumoUnidadAreaResult> ObtenerDatosInsumoUnidadArea([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Insumo", DbType="VarChar(600)")] string insumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaIni", DbType="Date")] System.Nullable<System.DateTime> fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaFin", DbType="Date")] System.Nullable<System.DateTime> fechaFin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unidad", DbType="Int")] System.Nullable<int> unidad)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), insumo, fechaIni, fechaFin, unidad);
		return ((ISingleResult<ObtenerDatosInsumoUnidadAreaResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Unidad")]
public partial class Unidad : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDUN;
	
	private string _NombreUN;
	
	private string _DireccionUN;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUNChanging(int value);
    partial void OnIDUNChanged();
    partial void OnNombreUNChanging(string value);
    partial void OnNombreUNChanged();
    partial void OnDireccionUNChanging(string value);
    partial void OnDireccionUNChanged();
    #endregion
	
	public Unidad()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this.OnIDUNChanging(value);
				this.SendPropertyChanging();
				this._IDUN = value;
				this.SendPropertyChanged("IDUN");
				this.OnIDUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this.OnNombreUNChanging(value);
				this.SendPropertyChanging();
				this._NombreUN = value;
				this.SendPropertyChanged("NombreUN");
				this.OnNombreUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionUN", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string DireccionUN
	{
		get
		{
			return this._DireccionUN;
		}
		set
		{
			if ((this._DireccionUN != value))
			{
				this.OnDireccionUNChanging(value);
				this.SendPropertyChanging();
				this._DireccionUN = value;
				this.SendPropertyChanged("DireccionUN");
				this.OnDireccionUNChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDU;
	
	private string _NombreU;
	
	private string _PassU;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUChanging(int value);
    partial void OnIDUChanged();
    partial void OnNombreUChanging(string value);
    partial void OnNombreUChanged();
    partial void OnPassUChanging(string value);
    partial void OnPassUChanged();
    #endregion
	
	public Usuario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreU", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string NombreU
	{
		get
		{
			return this._NombreU;
		}
		set
		{
			if ((this._NombreU != value))
			{
				this.OnNombreUChanging(value);
				this.SendPropertyChanging();
				this._NombreU = value;
				this.SendPropertyChanged("NombreU");
				this.OnNombreUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassU", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
	public string PassU
	{
		get
		{
			return this._PassU;
		}
		set
		{
			if ((this._PassU != value))
			{
				this.OnPassUChanging(value);
				this.SendPropertyChanging();
				this._PassU = value;
				this.SendPropertyChanged("PassU");
				this.OnPassUChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Documento")]
public partial class Documento : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDD;
	
	private System.DateTime _FechaCreacionD;
	
	private System.TimeSpan _HoraCreacionD;
	
	private System.DateTime _FechaPeriodoIniD;
	
	private System.DateTime _FechaPeriodoFinD;
	
	private string _RutaD;
	
	private string _NombreD;
	
	private byte _TipoD;
	
	private int _IDUN;
	
	private int _IDU;
	
	private System.Nullable<byte> _SubTipoD;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDChanging(int value);
    partial void OnIDDChanged();
    partial void OnFechaCreacionDChanging(System.DateTime value);
    partial void OnFechaCreacionDChanged();
    partial void OnHoraCreacionDChanging(System.TimeSpan value);
    partial void OnHoraCreacionDChanged();
    partial void OnFechaPeriodoIniDChanging(System.DateTime value);
    partial void OnFechaPeriodoIniDChanged();
    partial void OnFechaPeriodoFinDChanging(System.DateTime value);
    partial void OnFechaPeriodoFinDChanged();
    partial void OnRutaDChanging(string value);
    partial void OnRutaDChanged();
    partial void OnNombreDChanging(string value);
    partial void OnNombreDChanged();
    partial void OnTipoDChanging(byte value);
    partial void OnTipoDChanged();
    partial void OnIDUNChanging(int value);
    partial void OnIDUNChanged();
    partial void OnIDUChanging(int value);
    partial void OnIDUChanged();
    partial void OnSubTipoDChanging(System.Nullable<byte> value);
    partial void OnSubTipoDChanged();
    #endregion
	
	public Documento()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDD
	{
		get
		{
			return this._IDD;
		}
		set
		{
			if ((this._IDD != value))
			{
				this.OnIDDChanging(value);
				this.SendPropertyChanging();
				this._IDD = value;
				this.SendPropertyChanged("IDD");
				this.OnIDDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacionD", DbType="Date NOT NULL")]
	public System.DateTime FechaCreacionD
	{
		get
		{
			return this._FechaCreacionD;
		}
		set
		{
			if ((this._FechaCreacionD != value))
			{
				this.OnFechaCreacionDChanging(value);
				this.SendPropertyChanging();
				this._FechaCreacionD = value;
				this.SendPropertyChanged("FechaCreacionD");
				this.OnFechaCreacionDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraCreacionD", DbType="Time NOT NULL")]
	public System.TimeSpan HoraCreacionD
	{
		get
		{
			return this._HoraCreacionD;
		}
		set
		{
			if ((this._HoraCreacionD != value))
			{
				this.OnHoraCreacionDChanging(value);
				this.SendPropertyChanging();
				this._HoraCreacionD = value;
				this.SendPropertyChanged("HoraCreacionD");
				this.OnHoraCreacionDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoIniD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoIniD
	{
		get
		{
			return this._FechaPeriodoIniD;
		}
		set
		{
			if ((this._FechaPeriodoIniD != value))
			{
				this.OnFechaPeriodoIniDChanging(value);
				this.SendPropertyChanging();
				this._FechaPeriodoIniD = value;
				this.SendPropertyChanged("FechaPeriodoIniD");
				this.OnFechaPeriodoIniDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoFinD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoFinD
	{
		get
		{
			return this._FechaPeriodoFinD;
		}
		set
		{
			if ((this._FechaPeriodoFinD != value))
			{
				this.OnFechaPeriodoFinDChanging(value);
				this.SendPropertyChanging();
				this._FechaPeriodoFinD = value;
				this.SendPropertyChanged("FechaPeriodoFinD");
				this.OnFechaPeriodoFinDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaD", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string RutaD
	{
		get
		{
			return this._RutaD;
		}
		set
		{
			if ((this._RutaD != value))
			{
				this.OnRutaDChanging(value);
				this.SendPropertyChanging();
				this._RutaD = value;
				this.SendPropertyChanged("RutaD");
				this.OnRutaDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreD", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string NombreD
	{
		get
		{
			return this._NombreD;
		}
		set
		{
			if ((this._NombreD != value))
			{
				this.OnNombreDChanging(value);
				this.SendPropertyChanging();
				this._NombreD = value;
				this.SendPropertyChanged("NombreD");
				this.OnNombreDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoD", DbType="TinyInt NOT NULL")]
	public byte TipoD
	{
		get
		{
			return this._TipoD;
		}
		set
		{
			if ((this._TipoD != value))
			{
				this.OnTipoDChanging(value);
				this.SendPropertyChanging();
				this._TipoD = value;
				this.SendPropertyChanged("TipoD");
				this.OnTipoDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", DbType="Int NOT NULL")]
	public int IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this.OnIDUNChanging(value);
				this.SendPropertyChanging();
				this._IDUN = value;
				this.SendPropertyChanged("IDUN");
				this.OnIDUNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDU", DbType="Int NOT NULL")]
	public int IDU
	{
		get
		{
			return this._IDU;
		}
		set
		{
			if ((this._IDU != value))
			{
				this.OnIDUChanging(value);
				this.SendPropertyChanging();
				this._IDU = value;
				this.SendPropertyChanged("IDU");
				this.OnIDUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoD", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoD
	{
		get
		{
			return this._SubTipoD;
		}
		set
		{
			if ((this._SubTipoD != value))
			{
				this.OnSubTipoDChanging(value);
				this.SendPropertyChanging();
				this._SubTipoD = value;
				this.SendPropertyChanged("SubTipoD");
				this.OnSubTipoDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Variacion")]
public partial class Variacion : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDV;
	
	private int _CodigoV;
	
	private string _CategoriaV;
	
	private string _ProductoV;
	
	private string _UMV;
	
	private decimal _CostoUnitarioV;
	
	private decimal _DiferenciaV;
	
	private System.Nullable<System.DateTime> _FechaUltimoInventarioV;
	
	private int _IDD;
	
	private decimal _UtilizadoV;
	
	private System.Nullable<System.DateTime> _FechaIniPeriodoV;
	
	private System.Nullable<System.DateTime> _FechaFinPeriodoV;
	
	private System.Nullable<int> _IDUNV;
	
	private System.Nullable<byte> _SubTipoV;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDVChanging(int value);
    partial void OnIDVChanged();
    partial void OnCodigoVChanging(int value);
    partial void OnCodigoVChanged();
    partial void OnCategoriaVChanging(string value);
    partial void OnCategoriaVChanged();
    partial void OnProductoVChanging(string value);
    partial void OnProductoVChanged();
    partial void OnUMVChanging(string value);
    partial void OnUMVChanged();
    partial void OnCostoUnitarioVChanging(decimal value);
    partial void OnCostoUnitarioVChanged();
    partial void OnDiferenciaVChanging(decimal value);
    partial void OnDiferenciaVChanged();
    partial void OnFechaUltimoInventarioVChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaUltimoInventarioVChanged();
    partial void OnIDDChanging(int value);
    partial void OnIDDChanged();
    partial void OnUtilizadoVChanging(decimal value);
    partial void OnUtilizadoVChanged();
    partial void OnFechaIniPeriodoVChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaIniPeriodoVChanged();
    partial void OnFechaFinPeriodoVChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinPeriodoVChanged();
    partial void OnIDUNVChanging(System.Nullable<int> value);
    partial void OnIDUNVChanged();
    partial void OnSubTipoVChanging(System.Nullable<byte> value);
    partial void OnSubTipoVChanged();
    #endregion
	
	public Variacion()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDV
	{
		get
		{
			return this._IDV;
		}
		set
		{
			if ((this._IDV != value))
			{
				this.OnIDVChanging(value);
				this.SendPropertyChanging();
				this._IDV = value;
				this.SendPropertyChanged("IDV");
				this.OnIDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoV", DbType="Int NOT NULL")]
	public int CodigoV
	{
		get
		{
			return this._CodigoV;
		}
		set
		{
			if ((this._CodigoV != value))
			{
				this.OnCodigoVChanging(value);
				this.SendPropertyChanging();
				this._CodigoV = value;
				this.SendPropertyChanged("CodigoV");
				this.OnCodigoVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaV", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CategoriaV
	{
		get
		{
			return this._CategoriaV;
		}
		set
		{
			if ((this._CategoriaV != value))
			{
				this.OnCategoriaVChanging(value);
				this.SendPropertyChanging();
				this._CategoriaV = value;
				this.SendPropertyChanged("CategoriaV");
				this.OnCategoriaVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoV", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string ProductoV
	{
		get
		{
			return this._ProductoV;
		}
		set
		{
			if ((this._ProductoV != value))
			{
				this.OnProductoVChanging(value);
				this.SendPropertyChanging();
				this._ProductoV = value;
				this.SendPropertyChanged("ProductoV");
				this.OnProductoVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string UMV
	{
		get
		{
			return this._UMV;
		}
		set
		{
			if ((this._UMV != value))
			{
				this.OnUMVChanging(value);
				this.SendPropertyChanging();
				this._UMV = value;
				this.SendPropertyChanged("UMV");
				this.OnUMVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitarioV", DbType="Decimal(10,3) NOT NULL")]
	public decimal CostoUnitarioV
	{
		get
		{
			return this._CostoUnitarioV;
		}
		set
		{
			if ((this._CostoUnitarioV != value))
			{
				this.OnCostoUnitarioVChanging(value);
				this.SendPropertyChanging();
				this._CostoUnitarioV = value;
				this.SendPropertyChanged("CostoUnitarioV");
				this.OnCostoUnitarioVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiferenciaV", DbType="Decimal(10,3) NOT NULL")]
	public decimal DiferenciaV
	{
		get
		{
			return this._DiferenciaV;
		}
		set
		{
			if ((this._DiferenciaV != value))
			{
				this.OnDiferenciaVChanging(value);
				this.SendPropertyChanging();
				this._DiferenciaV = value;
				this.SendPropertyChanged("DiferenciaV");
				this.OnDiferenciaVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoInventarioV", DbType="Date")]
	public System.Nullable<System.DateTime> FechaUltimoInventarioV
	{
		get
		{
			return this._FechaUltimoInventarioV;
		}
		set
		{
			if ((this._FechaUltimoInventarioV != value))
			{
				this.OnFechaUltimoInventarioVChanging(value);
				this.SendPropertyChanging();
				this._FechaUltimoInventarioV = value;
				this.SendPropertyChanged("FechaUltimoInventarioV");
				this.OnFechaUltimoInventarioVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDD", DbType="Int NOT NULL")]
	public int IDD
	{
		get
		{
			return this._IDD;
		}
		set
		{
			if ((this._IDD != value))
			{
				this.OnIDDChanging(value);
				this.SendPropertyChanging();
				this._IDD = value;
				this.SendPropertyChanged("IDD");
				this.OnIDDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadoV", DbType="Decimal(10,3) NOT NULL")]
	public decimal UtilizadoV
	{
		get
		{
			return this._UtilizadoV;
		}
		set
		{
			if ((this._UtilizadoV != value))
			{
				this.OnUtilizadoVChanging(value);
				this.SendPropertyChanging();
				this._UtilizadoV = value;
				this.SendPropertyChanged("UtilizadoV");
				this.OnUtilizadoVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIniPeriodoV", DbType="Date")]
	public System.Nullable<System.DateTime> FechaIniPeriodoV
	{
		get
		{
			return this._FechaIniPeriodoV;
		}
		set
		{
			if ((this._FechaIniPeriodoV != value))
			{
				this.OnFechaIniPeriodoVChanging(value);
				this.SendPropertyChanging();
				this._FechaIniPeriodoV = value;
				this.SendPropertyChanged("FechaIniPeriodoV");
				this.OnFechaIniPeriodoVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinPeriodoV", DbType="Date")]
	public System.Nullable<System.DateTime> FechaFinPeriodoV
	{
		get
		{
			return this._FechaFinPeriodoV;
		}
		set
		{
			if ((this._FechaFinPeriodoV != value))
			{
				this.OnFechaFinPeriodoVChanging(value);
				this.SendPropertyChanging();
				this._FechaFinPeriodoV = value;
				this.SendPropertyChanged("FechaFinPeriodoV");
				this.OnFechaFinPeriodoVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNV", DbType="Int")]
	public System.Nullable<int> IDUNV
	{
		get
		{
			return this._IDUNV;
		}
		set
		{
			if ((this._IDUNV != value))
			{
				this.OnIDUNVChanging(value);
				this.SendPropertyChanging();
				this._IDUNV = value;
				this.SendPropertyChanged("IDUNV");
				this.OnIDUNVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoV", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoV
	{
		get
		{
			return this._SubTipoV;
		}
		set
		{
			if ((this._SubTipoV != value))
			{
				this.OnSubTipoVChanging(value);
				this.SendPropertyChanging();
				this._SubTipoV = value;
				this.SendPropertyChanged("SubTipoV");
				this.OnSubTipoVChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inventario")]
public partial class Inventario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDI;
	
	private int _CodigoI;
	
	private string _CategoriaI;
	
	private string _ProductoI;
	
	private string _UMI;
	
	private decimal _CostoUnitarioI;
	
	private decimal _InventarioInicialI;
	
	private decimal _ComprasI;
	
	private decimal _UtilizadoI;
	
	private decimal _InventarioFinalI;
	
	private System.DateTime _FechaUltimoInventarioI;
	
	private int _DetalleI;
	
	private int _IDD;
	
	private System.Nullable<System.DateTime> _FechaIniPeriodoI;
	
	private System.Nullable<System.DateTime> _FechaFinPeriodoI;
	
	private System.Nullable<int> _IDUNI;
	
	private System.Nullable<byte> _SubTipoI;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDIChanging(int value);
    partial void OnIDIChanged();
    partial void OnCodigoIChanging(int value);
    partial void OnCodigoIChanged();
    partial void OnCategoriaIChanging(string value);
    partial void OnCategoriaIChanged();
    partial void OnProductoIChanging(string value);
    partial void OnProductoIChanged();
    partial void OnUMIChanging(string value);
    partial void OnUMIChanged();
    partial void OnCostoUnitarioIChanging(decimal value);
    partial void OnCostoUnitarioIChanged();
    partial void OnInventarioInicialIChanging(decimal value);
    partial void OnInventarioInicialIChanged();
    partial void OnComprasIChanging(decimal value);
    partial void OnComprasIChanged();
    partial void OnUtilizadoIChanging(decimal value);
    partial void OnUtilizadoIChanged();
    partial void OnInventarioFinalIChanging(decimal value);
    partial void OnInventarioFinalIChanged();
    partial void OnFechaUltimoInventarioIChanging(System.DateTime value);
    partial void OnFechaUltimoInventarioIChanged();
    partial void OnDetalleIChanging(int value);
    partial void OnDetalleIChanged();
    partial void OnIDDChanging(int value);
    partial void OnIDDChanged();
    partial void OnFechaIniPeriodoIChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaIniPeriodoIChanged();
    partial void OnFechaFinPeriodoIChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinPeriodoIChanged();
    partial void OnIDUNIChanging(System.Nullable<int> value);
    partial void OnIDUNIChanged();
    partial void OnSubTipoIChanging(System.Nullable<byte> value);
    partial void OnSubTipoIChanged();
    #endregion
	
	public Inventario()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDI
	{
		get
		{
			return this._IDI;
		}
		set
		{
			if ((this._IDI != value))
			{
				this.OnIDIChanging(value);
				this.SendPropertyChanging();
				this._IDI = value;
				this.SendPropertyChanged("IDI");
				this.OnIDIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoI", DbType="Int NOT NULL")]
	public int CodigoI
	{
		get
		{
			return this._CodigoI;
		}
		set
		{
			if ((this._CodigoI != value))
			{
				this.OnCodigoIChanging(value);
				this.SendPropertyChanging();
				this._CodigoI = value;
				this.SendPropertyChanged("CodigoI");
				this.OnCodigoIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaI", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CategoriaI
	{
		get
		{
			return this._CategoriaI;
		}
		set
		{
			if ((this._CategoriaI != value))
			{
				this.OnCategoriaIChanging(value);
				this.SendPropertyChanging();
				this._CategoriaI = value;
				this.SendPropertyChanged("CategoriaI");
				this.OnCategoriaIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoI", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string ProductoI
	{
		get
		{
			return this._ProductoI;
		}
		set
		{
			if ((this._ProductoI != value))
			{
				this.OnProductoIChanging(value);
				this.SendPropertyChanging();
				this._ProductoI = value;
				this.SendPropertyChanged("ProductoI");
				this.OnProductoIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string UMI
	{
		get
		{
			return this._UMI;
		}
		set
		{
			if ((this._UMI != value))
			{
				this.OnUMIChanging(value);
				this.SendPropertyChanging();
				this._UMI = value;
				this.SendPropertyChanged("UMI");
				this.OnUMIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitarioI", DbType="Decimal(10,3) NOT NULL")]
	public decimal CostoUnitarioI
	{
		get
		{
			return this._CostoUnitarioI;
		}
		set
		{
			if ((this._CostoUnitarioI != value))
			{
				this.OnCostoUnitarioIChanging(value);
				this.SendPropertyChanging();
				this._CostoUnitarioI = value;
				this.SendPropertyChanged("CostoUnitarioI");
				this.OnCostoUnitarioIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioInicialI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioInicialI
	{
		get
		{
			return this._InventarioInicialI;
		}
		set
		{
			if ((this._InventarioInicialI != value))
			{
				this.OnInventarioInicialIChanging(value);
				this.SendPropertyChanging();
				this._InventarioInicialI = value;
				this.SendPropertyChanged("InventarioInicialI");
				this.OnInventarioInicialIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComprasI", DbType="Decimal(10,3) NOT NULL")]
	public decimal ComprasI
	{
		get
		{
			return this._ComprasI;
		}
		set
		{
			if ((this._ComprasI != value))
			{
				this.OnComprasIChanging(value);
				this.SendPropertyChanging();
				this._ComprasI = value;
				this.SendPropertyChanged("ComprasI");
				this.OnComprasIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadoI", DbType="Decimal(10,3) NOT NULL")]
	public decimal UtilizadoI
	{
		get
		{
			return this._UtilizadoI;
		}
		set
		{
			if ((this._UtilizadoI != value))
			{
				this.OnUtilizadoIChanging(value);
				this.SendPropertyChanging();
				this._UtilizadoI = value;
				this.SendPropertyChanged("UtilizadoI");
				this.OnUtilizadoIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioFinalI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioFinalI
	{
		get
		{
			return this._InventarioFinalI;
		}
		set
		{
			if ((this._InventarioFinalI != value))
			{
				this.OnInventarioFinalIChanging(value);
				this.SendPropertyChanging();
				this._InventarioFinalI = value;
				this.SendPropertyChanged("InventarioFinalI");
				this.OnInventarioFinalIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoInventarioI", DbType="Date NOT NULL")]
	public System.DateTime FechaUltimoInventarioI
	{
		get
		{
			return this._FechaUltimoInventarioI;
		}
		set
		{
			if ((this._FechaUltimoInventarioI != value))
			{
				this.OnFechaUltimoInventarioIChanging(value);
				this.SendPropertyChanging();
				this._FechaUltimoInventarioI = value;
				this.SendPropertyChanged("FechaUltimoInventarioI");
				this.OnFechaUltimoInventarioIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetalleI", DbType="Int NOT NULL")]
	public int DetalleI
	{
		get
		{
			return this._DetalleI;
		}
		set
		{
			if ((this._DetalleI != value))
			{
				this.OnDetalleIChanging(value);
				this.SendPropertyChanging();
				this._DetalleI = value;
				this.SendPropertyChanged("DetalleI");
				this.OnDetalleIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDD", DbType="Int NOT NULL")]
	public int IDD
	{
		get
		{
			return this._IDD;
		}
		set
		{
			if ((this._IDD != value))
			{
				this.OnIDDChanging(value);
				this.SendPropertyChanging();
				this._IDD = value;
				this.SendPropertyChanged("IDD");
				this.OnIDDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIniPeriodoI", DbType="Date")]
	public System.Nullable<System.DateTime> FechaIniPeriodoI
	{
		get
		{
			return this._FechaIniPeriodoI;
		}
		set
		{
			if ((this._FechaIniPeriodoI != value))
			{
				this.OnFechaIniPeriodoIChanging(value);
				this.SendPropertyChanging();
				this._FechaIniPeriodoI = value;
				this.SendPropertyChanged("FechaIniPeriodoI");
				this.OnFechaIniPeriodoIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinPeriodoI", DbType="Date")]
	public System.Nullable<System.DateTime> FechaFinPeriodoI
	{
		get
		{
			return this._FechaFinPeriodoI;
		}
		set
		{
			if ((this._FechaFinPeriodoI != value))
			{
				this.OnFechaFinPeriodoIChanging(value);
				this.SendPropertyChanging();
				this._FechaFinPeriodoI = value;
				this.SendPropertyChanged("FechaFinPeriodoI");
				this.OnFechaFinPeriodoIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNI", DbType="Int")]
	public System.Nullable<int> IDUNI
	{
		get
		{
			return this._IDUNI;
		}
		set
		{
			if ((this._IDUNI != value))
			{
				this.OnIDUNIChanging(value);
				this.SendPropertyChanging();
				this._IDUNI = value;
				this.SendPropertyChanged("IDUNI");
				this.OnIDUNIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoI", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoI
	{
		get
		{
			return this._SubTipoI;
		}
		set
		{
			if ((this._SubTipoI != value))
			{
				this.OnSubTipoIChanging(value);
				this.SendPropertyChanging();
				this._SubTipoI = value;
				this.SendPropertyChanged("SubTipoI");
				this.OnSubTipoIChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteInsumos")]
public partial class ReporteInsumos
{
	
	private System.DateTime _FechaPeriodoIniD;
	
	private System.DateTime _FechaPeriodoFinD;
	
	private System.Nullable<System.DateTime> _FechaPeriodoIniDV;
	
	private System.Nullable<System.DateTime> _FechaPeriodoFinDV;
	
	private System.Nullable<int> _IDUNV;
	
	private int _IDUN;
	
	private string _NombreUN;
	
	private int _IDI;
	
	private int _CodigoI;
	
	private string _CategoriaI;
	
	private string _ProductoI;
	
	private string _UMI;
	
	private decimal _CostoUnitarioI;
	
	private decimal _InventarioInicialI;
	
	private System.Nullable<decimal> _TotalInventarioInicialI;
	
	private decimal _ComprasI;
	
	private System.Nullable<decimal> _TotalComprasI;
	
	private decimal _UtilizadoI;
	
	private System.Nullable<decimal> _TotalUtilizadoI;
	
	private decimal _InventarioFinalI;
	
	private System.Nullable<decimal> _TotalInventarioFinalI;
	
	private System.Nullable<decimal> _DifrenciaInventarioInicialCompras;
	
	private System.Nullable<decimal> _TotlaDifrenciaInventarioInicialCompras;
	
	private System.DateTime _FechaUltimoInventarioI;
	
	private int _DetalleI;
	
	private System.Nullable<int> _IDV;
	
	private System.Nullable<decimal> _DiferenciaV;
	
	private System.Nullable<decimal> _UtilizadoV;
	
	private System.Nullable<decimal> _Cantidad;
	
	private System.Nullable<decimal> _Perdida_Favor;
	
	private string _NombreD;
	
	private System.Nullable<byte> _SubTipoD;
	
	public ReporteInsumos()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoIniD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoIniD
	{
		get
		{
			return this._FechaPeriodoIniD;
		}
		set
		{
			if ((this._FechaPeriodoIniD != value))
			{
				this._FechaPeriodoIniD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoFinD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoFinD
	{
		get
		{
			return this._FechaPeriodoFinD;
		}
		set
		{
			if ((this._FechaPeriodoFinD != value))
			{
				this._FechaPeriodoFinD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoIniDV", DbType="Date")]
	public System.Nullable<System.DateTime> FechaPeriodoIniDV
	{
		get
		{
			return this._FechaPeriodoIniDV;
		}
		set
		{
			if ((this._FechaPeriodoIniDV != value))
			{
				this._FechaPeriodoIniDV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoFinDV", DbType="Date")]
	public System.Nullable<System.DateTime> FechaPeriodoFinDV
	{
		get
		{
			return this._FechaPeriodoFinDV;
		}
		set
		{
			if ((this._FechaPeriodoFinDV != value))
			{
				this._FechaPeriodoFinDV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNV", DbType="Int")]
	public System.Nullable<int> IDUNV
	{
		get
		{
			return this._IDUNV;
		}
		set
		{
			if ((this._IDUNV != value))
			{
				this._IDUNV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", DbType="Int NOT NULL")]
	public int IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this._IDUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this._NombreUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDI", DbType="Int NOT NULL")]
	public int IDI
	{
		get
		{
			return this._IDI;
		}
		set
		{
			if ((this._IDI != value))
			{
				this._IDI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoI", DbType="Int NOT NULL")]
	public int CodigoI
	{
		get
		{
			return this._CodigoI;
		}
		set
		{
			if ((this._CodigoI != value))
			{
				this._CodigoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaI", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CategoriaI
	{
		get
		{
			return this._CategoriaI;
		}
		set
		{
			if ((this._CategoriaI != value))
			{
				this._CategoriaI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoI", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string ProductoI
	{
		get
		{
			return this._ProductoI;
		}
		set
		{
			if ((this._ProductoI != value))
			{
				this._ProductoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string UMI
	{
		get
		{
			return this._UMI;
		}
		set
		{
			if ((this._UMI != value))
			{
				this._UMI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitarioI", DbType="Decimal(10,3) NOT NULL")]
	public decimal CostoUnitarioI
	{
		get
		{
			return this._CostoUnitarioI;
		}
		set
		{
			if ((this._CostoUnitarioI != value))
			{
				this._CostoUnitarioI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioInicialI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioInicialI
	{
		get
		{
			return this._InventarioInicialI;
		}
		set
		{
			if ((this._InventarioInicialI != value))
			{
				this._InventarioInicialI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalInventarioInicialI", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> TotalInventarioInicialI
	{
		get
		{
			return this._TotalInventarioInicialI;
		}
		set
		{
			if ((this._TotalInventarioInicialI != value))
			{
				this._TotalInventarioInicialI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComprasI", DbType="Decimal(10,3) NOT NULL")]
	public decimal ComprasI
	{
		get
		{
			return this._ComprasI;
		}
		set
		{
			if ((this._ComprasI != value))
			{
				this._ComprasI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalComprasI", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> TotalComprasI
	{
		get
		{
			return this._TotalComprasI;
		}
		set
		{
			if ((this._TotalComprasI != value))
			{
				this._TotalComprasI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadoI", DbType="Decimal(10,3) NOT NULL")]
	public decimal UtilizadoI
	{
		get
		{
			return this._UtilizadoI;
		}
		set
		{
			if ((this._UtilizadoI != value))
			{
				this._UtilizadoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalUtilizadoI", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> TotalUtilizadoI
	{
		get
		{
			return this._TotalUtilizadoI;
		}
		set
		{
			if ((this._TotalUtilizadoI != value))
			{
				this._TotalUtilizadoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioFinalI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioFinalI
	{
		get
		{
			return this._InventarioFinalI;
		}
		set
		{
			if ((this._InventarioFinalI != value))
			{
				this._InventarioFinalI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalInventarioFinalI", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> TotalInventarioFinalI
	{
		get
		{
			return this._TotalInventarioFinalI;
		}
		set
		{
			if ((this._TotalInventarioFinalI != value))
			{
				this._TotalInventarioFinalI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DifrenciaInventarioInicialCompras", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> DifrenciaInventarioInicialCompras
	{
		get
		{
			return this._DifrenciaInventarioInicialCompras;
		}
		set
		{
			if ((this._DifrenciaInventarioInicialCompras != value))
			{
				this._DifrenciaInventarioInicialCompras = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotlaDifrenciaInventarioInicialCompras", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> TotlaDifrenciaInventarioInicialCompras
	{
		get
		{
			return this._TotlaDifrenciaInventarioInicialCompras;
		}
		set
		{
			if ((this._TotlaDifrenciaInventarioInicialCompras != value))
			{
				this._TotlaDifrenciaInventarioInicialCompras = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoInventarioI", DbType="Date NOT NULL")]
	public System.DateTime FechaUltimoInventarioI
	{
		get
		{
			return this._FechaUltimoInventarioI;
		}
		set
		{
			if ((this._FechaUltimoInventarioI != value))
			{
				this._FechaUltimoInventarioI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetalleI", DbType="Int NOT NULL")]
	public int DetalleI
	{
		get
		{
			return this._DetalleI;
		}
		set
		{
			if ((this._DetalleI != value))
			{
				this._DetalleI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDV", DbType="Int")]
	public System.Nullable<int> IDV
	{
		get
		{
			return this._IDV;
		}
		set
		{
			if ((this._IDV != value))
			{
				this._IDV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiferenciaV", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> DiferenciaV
	{
		get
		{
			return this._DiferenciaV;
		}
		set
		{
			if ((this._DiferenciaV != value))
			{
				this._DiferenciaV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadoV", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> UtilizadoV
	{
		get
		{
			return this._UtilizadoV;
		}
		set
		{
			if ((this._UtilizadoV != value))
			{
				this._UtilizadoV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this._Cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Perdida/Favor]", Storage="_Perdida_Favor", DbType="Decimal(10,3)")]
	public System.Nullable<decimal> Perdida_Favor
	{
		get
		{
			return this._Perdida_Favor;
		}
		set
		{
			if ((this._Perdida_Favor != value))
			{
				this._Perdida_Favor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreD", DbType="VarChar(250)")]
	public string NombreD
	{
		get
		{
			return this._NombreD;
		}
		set
		{
			if ((this._NombreD != value))
			{
				this._NombreD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoD", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoD
	{
		get
		{
			return this._SubTipoD;
		}
		set
		{
			if ((this._SubTipoD != value))
			{
				this._SubTipoD = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventarioDocumento")]
public partial class InventarioDocumento
{
	
	private int _IDI;
	
	private int _CodigoI;
	
	private string _CategoriaI;
	
	private string _ProductoI;
	
	private string _UMI;
	
	private decimal _CostoUnitarioI;
	
	private decimal _InventarioInicialI;
	
	private decimal _ComprasI;
	
	private decimal _UtilizadoI;
	
	private decimal _InventarioFinalI;
	
	private System.DateTime _FechaUltimoInventarioI;
	
	private int _DetalleI;
	
	private int _IDD;
	
	private System.Nullable<System.DateTime> _FechaIniPeriodoI;
	
	private System.Nullable<System.DateTime> _FechaFinPeriodoI;
	
	private System.Nullable<int> _IDUNI;
	
	private System.Nullable<byte> _SubTipoI;
	
	private System.DateTime _FechaPeriodoIniD;
	
	private System.DateTime _FechaPeriodoFinD;
	
	private int _IDUN;
	
	private System.Nullable<byte> _SubTipoD;
	
	public InventarioDocumento()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDI", DbType="Int NOT NULL")]
	public int IDI
	{
		get
		{
			return this._IDI;
		}
		set
		{
			if ((this._IDI != value))
			{
				this._IDI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoI", DbType="Int NOT NULL")]
	public int CodigoI
	{
		get
		{
			return this._CodigoI;
		}
		set
		{
			if ((this._CodigoI != value))
			{
				this._CodigoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaI", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string CategoriaI
	{
		get
		{
			return this._CategoriaI;
		}
		set
		{
			if ((this._CategoriaI != value))
			{
				this._CategoriaI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoI", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string ProductoI
	{
		get
		{
			return this._ProductoI;
		}
		set
		{
			if ((this._ProductoI != value))
			{
				this._ProductoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string UMI
	{
		get
		{
			return this._UMI;
		}
		set
		{
			if ((this._UMI != value))
			{
				this._UMI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitarioI", DbType="Decimal(10,3) NOT NULL")]
	public decimal CostoUnitarioI
	{
		get
		{
			return this._CostoUnitarioI;
		}
		set
		{
			if ((this._CostoUnitarioI != value))
			{
				this._CostoUnitarioI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioInicialI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioInicialI
	{
		get
		{
			return this._InventarioInicialI;
		}
		set
		{
			if ((this._InventarioInicialI != value))
			{
				this._InventarioInicialI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComprasI", DbType="Decimal(10,3) NOT NULL")]
	public decimal ComprasI
	{
		get
		{
			return this._ComprasI;
		}
		set
		{
			if ((this._ComprasI != value))
			{
				this._ComprasI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadoI", DbType="Decimal(10,3) NOT NULL")]
	public decimal UtilizadoI
	{
		get
		{
			return this._UtilizadoI;
		}
		set
		{
			if ((this._UtilizadoI != value))
			{
				this._UtilizadoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventarioFinalI", DbType="Decimal(10,3) NOT NULL")]
	public decimal InventarioFinalI
	{
		get
		{
			return this._InventarioFinalI;
		}
		set
		{
			if ((this._InventarioFinalI != value))
			{
				this._InventarioFinalI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimoInventarioI", DbType="Date NOT NULL")]
	public System.DateTime FechaUltimoInventarioI
	{
		get
		{
			return this._FechaUltimoInventarioI;
		}
		set
		{
			if ((this._FechaUltimoInventarioI != value))
			{
				this._FechaUltimoInventarioI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetalleI", DbType="Int NOT NULL")]
	public int DetalleI
	{
		get
		{
			return this._DetalleI;
		}
		set
		{
			if ((this._DetalleI != value))
			{
				this._DetalleI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDD", DbType="Int NOT NULL")]
	public int IDD
	{
		get
		{
			return this._IDD;
		}
		set
		{
			if ((this._IDD != value))
			{
				this._IDD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIniPeriodoI", DbType="Date")]
	public System.Nullable<System.DateTime> FechaIniPeriodoI
	{
		get
		{
			return this._FechaIniPeriodoI;
		}
		set
		{
			if ((this._FechaIniPeriodoI != value))
			{
				this._FechaIniPeriodoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinPeriodoI", DbType="Date")]
	public System.Nullable<System.DateTime> FechaFinPeriodoI
	{
		get
		{
			return this._FechaFinPeriodoI;
		}
		set
		{
			if ((this._FechaFinPeriodoI != value))
			{
				this._FechaFinPeriodoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNI", DbType="Int")]
	public System.Nullable<int> IDUNI
	{
		get
		{
			return this._IDUNI;
		}
		set
		{
			if ((this._IDUNI != value))
			{
				this._IDUNI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoI", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoI
	{
		get
		{
			return this._SubTipoI;
		}
		set
		{
			if ((this._SubTipoI != value))
			{
				this._SubTipoI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoIniD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoIniD
	{
		get
		{
			return this._FechaPeriodoIniD;
		}
		set
		{
			if ((this._FechaPeriodoIniD != value))
			{
				this._FechaPeriodoIniD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPeriodoFinD", DbType="Date NOT NULL")]
	public System.DateTime FechaPeriodoFinD
	{
		get
		{
			return this._FechaPeriodoFinD;
		}
		set
		{
			if ((this._FechaPeriodoFinD != value))
			{
				this._FechaPeriodoFinD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUN", DbType="Int NOT NULL")]
	public int IDUN
	{
		get
		{
			return this._IDUN;
		}
		set
		{
			if ((this._IDUN != value))
			{
				this._IDUN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoD", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoD
	{
		get
		{
			return this._SubTipoD;
		}
		set
		{
			if ((this._SubTipoD != value))
			{
				this._SubTipoD = value;
			}
		}
	}
}

public partial class ObtenerDatosInsumoUnidadResult
{
	
	private System.Nullable<decimal> _Variacion;
	
	private string _NombreUN;
	
	public ObtenerDatosInsumoUnidadResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variacion", DbType="Decimal(38,3)")]
	public System.Nullable<decimal> Variacion
	{
		get
		{
			return this._Variacion;
		}
		set
		{
			if ((this._Variacion != value))
			{
				this._Variacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string NombreUN
	{
		get
		{
			return this._NombreUN;
		}
		set
		{
			if ((this._NombreUN != value))
			{
				this._NombreUN = value;
			}
		}
	}
}

public partial class ObtenerDatosInsumoUnidadAreaResult
{
	
	private System.Nullable<decimal> _Variacion;
	
	private System.Nullable<byte> _SubTipoD;
	
	public ObtenerDatosInsumoUnidadAreaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variacion", DbType="Decimal(38,3)")]
	public System.Nullable<decimal> Variacion
	{
		get
		{
			return this._Variacion;
		}
		set
		{
			if ((this._Variacion != value))
			{
				this._Variacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTipoD", DbType="TinyInt")]
	public System.Nullable<byte> SubTipoD
	{
		get
		{
			return this._SubTipoD;
		}
		set
		{
			if ((this._SubTipoD != value))
			{
				this._SubTipoD = value;
			}
		}
	}
}
#pragma warning restore 1591
